# Site settings
baseurl = "https://azuretechtalk.net/"
languageCode = "en-us"
title = "#AzureTechTalk"
theme = "spectre-pixel"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  name = "#AzureTechTalk"
  altName = ""
  description = ""
  bio = "We talk about Azure, deploy stuff and have fun"
  enableRSS = true

  # Author information in posts
  aboutAuthor = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = [
    "https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css"
  ]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
	home = ""
	subscribe = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	copyright = "Frank Oltmanns-Mack, Max Melcher, 2021"

	# 404 page
	title404 = ""
	subtitle404 = ""

# Add additional social link entries underneath
[social]
#	email    = "john.doe@email.com"
	github   = "https://www.github.com/maxmelcher/azuretechtalk"
	linkedin1 = "https://www.linkedin.com/maxmelcher"
	linkedin2 = "https://www.linkedin.com/frankoltmannsmack"
	twitter  = "https://www.twitter.com/azuretechtalk"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
unsafe= true